version: '2'
services:
  users:
    build:
      context: '.'
    links:
      - postgres
      - redis
    volumes:
     - ".:/app/users/"
    working_dir: /app/users
    command: [rails, server, -p, "3000", -b, 0.0.0.0]
    ports:
    - "3000:3000"
  
  postgres:
    image: postgres:9.5
    # volumes:
    #   - "./data/users:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_DB: redis_token
      POSTGRES_USER: redis
      POSTGRES_PASSWORD: redis
      PGDATA: /var/lib/postgres/data/pgdata

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"

volumes:
  redis: